cree = {
    "tanisi": "hello",
    "Nipiy": "water",
    "Iskwew": "woman",
    "Wâpakwanîs": "flower",
    "Wâsênikan": "window",
    "Picikwâs": "apple",
    "Osâwâs": "orange",
    "Mistatim": "horse",
    "Akihtâson": "number",
    "Minihkwewin" : "drink",
    "Nakata" : "leave" ,
    "Askihtak" : "green" ,
    "Osâwêkin" : "yellow",
    "ka peyakoskânowihk" : "tribe",
    "Kihcikamiy" : "ocean",
    "waciy" : "mountain",
    "Maskosiy" : "grass",
    "Sîpîy" : "river",
    "Ayisiyinowak" : "people"
}
ojibwe = {
    "Boozhoo" : "Welcome",
    "Moozhawgan": "Scissors",
    "Nizhawsi": "Seven",
    "Migizi": "Eagle", 
    "Nigig": "Otter",
    "Nibi": "Water", 
    "Aki": "Earth",
    "Wabigon": "Flower",
    "Makade": "Black",
    "Ikwe": "Woman",
    "Kitigan": "Plant",
    "Ozaawi": "Yellow",
    "Maajaa": "Leave",
    "Animosh": "Tobacco",
    "Migwech": "Thank you",
    "niswi": "Three",
    "Ajitamo": "Squirrel", 
    "Waboos": "Rabbit",
    "Oninj": "Finger", 
    "Waabishki": "White"
}
mont = {
    "Nishtu" : "three",
    "atshimipuk" : " snake",
    "Ishkueu" : "woman",
    "mush" : "moose",
    "uâpush" : "rabbit",
    "Uapau " : "white" ,
    "Uishauau" : "yellow" ,
    "misinak" : "turtles",
    "Kashteuau" : "black" ,
    "nishpishkun" :" shoulder",
    "Pûshit" : "leave" ,
    "kapelikushkueu " : "horse" , 
    "ninuai" : " cheek",
    "uasheshkunau" : "green" ,
    "apikushish": " mouse",
    "atiku" : "caribou",
    "nukutshash" : "squirrel" ,
    "kâku" : "porcupine",
    "nininitshititshan" : " finger",
    "nishuasht" : " seven"
}